## Vectorisation

In [3]:
import numpy as np
w = np.array([1.0, 2.5, -3.3])
b = 7
x = np.array([10,20,30])

f = np.dot(w,x) + b
print(f)


-32.0


## Dimensions of an Array

In [7]:
# NumPy routines which allocate memory and fill arrays with value
a = np.zeros(4);                print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,));             print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
print()
print("This has created a 1-D vector with four elements. a.shape returns the dimensions. Here we see a.shape = (4,) indicating a 1-D array with 4 elements.")

print()
print("2-D ARRAY, 4 ROWS 2 COLUMNS")
a = np.zeros((4,2));             print(f"np.zeros(4,2) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
print()
print("3-D ARRAY, 4 SHEETS, WITH 2 ROWS AND 2 COLUMNS FOR EACH SHEET")
a = np.zeros((4,2,2));             print(f"np.zeros(4,2,2) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")



np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.18952972 0.2699789  0.89905924 0.46238372], a shape = (4,), a data type = float64

This has created a 1-D vector with four elements. a.shape returns the dimensions. Here we see a.shape = (4,) indicating a 1-D array with 4 elements.

2-D ARRAY, 4 ROWS 2 COLUMNS
np.zeros(4,2) :  a = [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]], a shape = (4, 2), a data type = float64

3-D ARRAY, 4 SHEETS, WITH 2 ROWS AND 2 COLUMNS FOR EACH SHEET
np.zeros(4,2,2) :  a = [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]], a shape = (4, 2, 2), a data type = float64
