In [6]:
import numpy as np
x_train = np.array([1,2,3,4,5,6,7])
y_train = np.array([100,200,300,400,500,600,700])
print (x_train)
print (y_train)


[1 2 3 4 5 6 7]
[100 200 300 400 500 600 700]


In [7]:
print(x_train.shape)
m = x_train.shape[0]
print(f"The total number of training examples for this model is {m}")
print(len(x_train))

(7,)
The total number of training examples for this model is 7
7


In [18]:
print(range(10))
np1 = np.arange(10)
print(np1)
np2 = np.arange(0,10,2)
print(np2)
np3 = np.zeros(10)#ONE DIMENSIONAL ARRAY
print(np3)
np4 = np.zeros((2,5))#TWO DIMENSIONAL ARRAY WITH 5 ZEROS IN EACH DIMENSION
print(np4)
print(np4.shape)
np5 = np.full(10,7)#FILLING AN ARRAY WITH 10 SEVEN'S
print(np5)
np6 = np.full((2,5),7)#FILLING A TWO DIMENSIONAL ARRAY WITH 5 SEVEN'S 
                      #IN EACH DIMENSION
print(np6)
my_list = [1,2,3,4,5]
np7 = np.array(my_list)#CONVERTS A LIST TO A NUMPY ARRAY
print(np7)
print(np7[0])#PRINTS THE FIRST ELEMENT OF THE ARRAY JUST LIKE A LIST
print(np7[1])#PRINTS THE SECOND ELEMENT OF THE ARRAY JUST LIKE A LIST
print(np2[-1])#PRINTS THE LAST ELEMENT OF THE ARRAY JUST LIKE A LIST

range(0, 10)
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(2, 5)
[7 7 7 7 7 7 7 7 7 7]
[[7 7 7 7 7]
 [7 7 7 7 7]]
[1 2 3 4 5]
1
2
8


## Slicing NumPy Arrays

In [ ]:
#SLICING CREATES AN ARRAY OF INDICES USING A SET OF THREE VALUES (START:STOP:STEP)
print(np7[1:4])#PRINTS ELEMENTS FROM INDEX 1 TO 3(2ND ITEM TO THE 4TH ITEM)
print(np1[4:])#PRINTS ELEMENTS FROM INDEX 4 TO THE END OF THE ARRAY
              #(5TH ITEM TO THE LAST ITEM)
print(np1[:4])#PRINTS ELEMENTS FROM THE START OF THE ARRAY TO INDEX 3
              #(1ST ITEM TO THE 4TH ITEM)
print(np1[:-3])#PRINTS ELEMENTS FROM THE 4TH ITEM OF THE ARRAY COUNTING FROM
               #THE RIGHT TO THE FIRST ELEMENT OF THE ARRAY
print(np1[:3])#SINCE THE STOP VALUE IS +, WHILE THE START VALUE IS BLANK, THIS PRINTS 
              #ELEMENTS BELOW INDEX 3, WHICH IS THE 4TH ELEMENT OF THE ARRAY COUNTING 
              #FROM THE LEFT
print(np1[:])#PRINTS ALL THE ELEMENTS IN THE ARRAY. IT'S BASICALLY A COPY OF THE ARRAY

print(np1[-3:-1])#PRINTS FROM THE 2ND ITEM OF THE ARRY COUNTING FROM THE RIGHT
                 #TO THE 3RD ITEM OF THE ARRAY COUNTING FROM THE RIGHT AS WELL
print(np1[::2])#PRINTS EVERY SECOND ELEMENT OF THE ARRAY STARTING FROM THE FIRST
print(np1[1::2])#PRINTS EVERY SECOND ELEMENT OF THE ARRAY STARTING
                #FROM THE SECOND
print(np1[1:6:2])#PRINTS EVERY SECOND ELEMENT OF THE ARRAY STARTING FROM THE SECOND
                 #ELEMENT TO THE 6TH ELEMENT OF THE ARRAY
print(np1[::-1])#PRINTS THE ARRAY IN REVERSE ORDER
print(np1[::-2])#PRINTS EVERY SECOND ELEMENT OF THE ARRAY IN REVERSE ORDER

np8 = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]])#A 2D ARRAY
print(np8[1,2])
print(np8[0:1, 1:3])
print(np8[0:2, 1:3])

[2 3 4]
[4 5 6 7 8 9]
[0 1 2 3]
[0 1 2 3 4 5 6]
[7 8]
[0 2 4 6 8]
[1 3 5 7 9]
[1 3 5]
[9 8 7 6 5 4 3 2 1 0]
[9 7 5 3 1]
8
[[2 3]]
[[2 3]
 [7 8]]


In [25]:
#DEMO: 2D vs 3D NUMPY ARRAYS

#--- 2D ARRAY: rows and columns, like a spreadsheet ---
arr2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("2D array:")
print(arr2d)
print("shape:", arr2d.shape)#(2, 3) -> 2 rows, 3 columns
print("ndim:", arr2d.ndim)#2 dimensions
print("element at row 0, col 1:", arr2d[0, 1])#2

print()

#--- 3D ARRAY: a stack of 2D arrays, like sheets in a book ---
arr3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print("3D array:")
print(arr3d)
print("shape:", arr3d.shape)#(2, 2, 2) -> 2 sheets, each 2 rows x 2 cols
print("ndim:", arr3d.ndim)#3 dimensions
print("element at sheet 1, row 0, col 1:", arr3d[1, 0, 1])#6


2D array:
[[1 2 3]
 [4 5 6]]
shape: (2, 3)
ndim: 2
element at row 0, col 1: 2

3D array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape: (2, 2, 2)
ndim: 3
element at sheet 1, row 0, col 1: 6


In [ ]:
#UNIVERSAL FUNCTIONS IN NUMPY
np1 = np.array([-3,-2,-1,1,2,3,4,5,6,7,8,9])
print(np1)
np2 = np.array([1,2,3,4,5,6,7,8,9,10])
print()
print(np.sqrt(np2))#SQUARE ROOT OF EACH ELEMENT IN THE ARRAY
print(np.exp(np1))#EXPONENTIAL OF EACH ELEMENT IN THE ARRAY
print(np.absolute(np1))#ABSOLUTE VALUE OF EACH ELEMENT IN THE ARRAY
print(np.max(np1))#MAXIMUM ELEMENT IN THE ARRAY
print(np.min(np1))#MINIMUM ELEMENT IN THE ARRAY
print(np.sign(np1))#SIGN OF EACH ELEMENT IN THE ARRAY(WHETHER +, -, OR 0)
print(np.sin(np1))#SINE OF EACH ELEMENT IN THE ARRAY
print(np.cos(np1))#COSINE OF EACH ELEMENT IN THE ARRAY
print(np.tan(np1))#TANGENT OF EACH ELEMENT IN THE ARRAY
print(np.log(np2))#NATURAL LOGARITHM OF EACH ELEMENT IN THE ARRAY

[-3 -2 -1  1  2  3  4  5  6  7  8  9]

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[4.97870684e-02 1.35335283e-01 3.67879441e-01 2.71828183e+00
 7.38905610e+00 2.00855369e+01 5.45981500e+01 1.48413159e+02
 4.03428793e+02 1.09663316e+03 2.98095799e+03 8.10308393e+03]
[3 2 1 1 2 3 4 5 6 7 8 9]
9
-3
[-1 -1 -1  1  1  1  1  1  1  1  1  1]
[-0.14112001 -0.90929743 -0.84147098  0.84147098  0.90929743  0.14112001
 -0.7568025  -0.95892427 -0.2794155   0.6569866   0.98935825  0.41211849]
[-0.9899925  -0.41614684  0.54030231  0.54030231 -0.41614684 -0.9899925
 -0.65364362  0.28366219  0.96017029  0.75390225 -0.14550003 -0.91113026]
[ 0.14254654  2.18503986 -1.55740772  1.55740772 -2.18503986 -0.14254654
  1.15782128 -3.38051501 -0.29100619  0.87144798 -6.79971146 -0.45231566]


In [42]:
import numpy as np
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
np2 = np1.view()#CREATES A VIEW OF THE ARRAY, NOT A COPY.
                #MEANING THAT IF YOU CHANGE THE VIEW, THE 
                #ORIGINAL ARRAY WILL ALSO BE CHANGED. THEY'RE CONNECTED
print(f"Original array: {np1}")
print(f"View array: {np2}")

np1[0] = 100#CHANGING THE FIRST ELEMENT OF THE ORIGINAL ARRAY
print(f"Original array after change: {np1}")
print(f"View array after original change: {np2}")#THE VIEW ARRAY ALSO CHANGES
print()
np3 = np1.copy()#CREATES A COPY OF THE ARRAY. MEANING THAT IF YOU CHANGE THE COPY,
                #THE ORIGINAL ARRAY WILL NOT BE CHANGED. THEY'RE NOT CONNECTED
print(f"Original array: {np1}")
print(f"Copy array: {np3}")

np1[7] = 700#CHANGING THE EIGHTH ELEMENT OF THE ORIGINAL ARRAY
print(f"Original array after change: {np1}")
print(f"Copy array after original change: {np3}")#THE COPY ARRAY DOES NOT CHANGE
print(f"View array after original change: {np2}")#THE VIEW ARRAY ALSO CHANGES

#NB: CHANGING THE VIEW ARRAY WILL ALSO CHANGE THE ORIGINAL ARRAY.

Original array: [0 1 2 3 4 5 6 7 8 9]
View array: [0 1 2 3 4 5 6 7 8 9]
Original array after change: [100   1   2   3   4   5   6   7   8   9]
View array after original change: [100   1   2   3   4   5   6   7   8   9]

Original array: [100   1   2   3   4   5   6   7   8   9]
Copy array: [100   1   2   3   4   5   6   7   8   9]
Original array after change: [100   1   2   3   4   5   6 700   8   9]
Copy array after original change: [100   1   2   3   4   5   6   7   8   9]
View array after original change: [100   1   2   3   4   5   6 700   8   9]


## Changing the Dimension of an array

In [50]:
import numpy as np
np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])#THIS IS A ONE DIMENSIONAL
                                                    #ARRAY WITH 15 ELEMENTS
print(np1)
print(np1.shape)
print()
np2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])#THIS IS A TWO DIMENSIONAL    
                                                #ARRAY WITH 2 ROWS AND 6 COLUMNS
                                                #OR 6 ELEMENTS.
print(np2)
print(np2.shape)
print()
np3 = np1.reshape(3,4)#RESHAPES THE ONE DIMENSIONAL ARRAY INTO A TWO DIMENSIONAL
                      #ARRAY WITH 3 ROWS AND 4 COLUMNS OR 4 ELEMENTS.
print(np3)
print(np3.shape)
print()

np4 = np1.reshape(2,3,2)#RESHAPES THE ONE DIMENSIONAL ARRAY INTO A THREE DIMENSIONAL
                        #ARRAY WITH 2 SHEETS, 3 ROWS AND 2 COLUMNS OR 2 ELEMENTS.
print(np4)
print(np4.shape)
print()

np5 = np4.reshape(-1)#RESHAPES THE THREE DIMENSIONAL ARRAY INTO A ONE DIMENSIONAL
                     #ARRAY WITH 12 ELEMENTS.
print(np5)
print(np5.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


## Iterating through NumPy arrays

In [78]:
import numpy as np
np1 = np.array([1,2,3,4,5,6,7,8,9,10])#1-D ARRAY
print(np1)
for num in np1:
    print(num**2)#PRINTS THE SQUARE OF EACH ELEMENT IN THE ARRAY

print()
np2 = np1.reshape(2,5)
print(np2)
print(np2.shape)
print()
for num_1 in np2:
    for num_2 in num_1:
        print(num_2**2)#PRINTS THE SQUARE OF EACH ELEMENT IN THE 2-D ARRAY

np3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])#3-D ARRAY
print(np3)  
print(np3.shape)
print()
for num_1 in np3:
    print(num_1)
'''
for num_1 in np3:
    for num_2 in num_1:
        for num_3 in num_2:
            print(num_3**2)#PRINTS THE SQUARE OF EACH ELEMENT IN THE 3-D ARRAY
'''
for x in np.nditer(np3):
    print(x**2)#PRINTS THE SQUARE OF EACH ELEMENT IN THE 3-D ARRAY

[ 1  2  3  4  5  6  7  8  9 10]
1
4
9
16
25
36
49
64
81
100

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)

1
4
9
16
25
36
49
64
81
100
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
4
9
16
25
36
49
64
81
100
121
144


## Sorting NumPy arrays

In [79]:
import numpy as np
x_train = np.array([3,7,5,1,9,2,8,4,6,0])
print(f"x_train: {x_train}")
print(f"Sorted x_train: {np.sort(x_train)}")#PRINTS THE SORTED ARRAY
print()

y_train = np.array(["Oppong", "Yaw", "Nhyira", "Adom", "Kwame"])
print(f"y_train: {y_train}")
print(f"Sorted y_train: {np.sort(y_train)}")#PRINTS THE SORTED ARRAY
print()

z_train = np.array([True, False, True, False, True])
print(f"z_train: {z_train}")
print(f"Sorted z_train: {np.sort(z_train)}")#PRINTS THE SORTED ARRAY
print()

np1 = x_train.reshape(2,5)
print(np1)
print(np.sort(np1))


x_train: [3 7 5 1 9 2 8 4 6 0]
Sorted x_train: [0 1 2 3 4 5 6 7 8 9]

y_train: ['Oppong' 'Yaw' 'Nhyira' 'Adom' 'Kwame']
Sorted y_train: ['Adom' 'Kwame' 'Nhyira' 'Oppong' 'Yaw']

z_train: [ True False  True False  True]
Sorted z_train: [False False  True  True  True]

[[3 7 5 1 9]
 [2 8 4 6 0]]
[[1 3 5 7 9]
 [0 2 4 6 8]]


## Searching through a NumPy array

In [ ]:
import numpy as np
x_train = np.array([1,2,3,4,5,6,7,4])
loc_x_train = np.where(x_train == 4)#FINDS THE INDEX OF THE ELEMENT IN THE ARRAY
print(x_train)
print(loc_x_train)#PRINTS THE INDEX OF THE ELEMENT IN THE ARRAY
print(x_train[loc_x_train])#PRINTS THE ELEMENT IN THE ARRAY AT THE INDEX FOUND
print(x_train[loc_x_train[0]])#PRINTS THE ELEMENT IN THE ARRAY AT THE INDEX FOUND
print()
x = np.where(x_train % 2 == 0)#FINDS THE INDEX OF ALL EVEN ELEMENTS IN THE ARRAY
print(x)
z = np.where(x_train % 2 != 0)#FINDS THE INDEX OF ALL ODD ELEMENTS IN THE ARRAY
print(z)
#THE WHERE FUNCTION RETURNS THE INDEX OF THE ELEMENTS THAT SATISFY THE CONDITION
#IN THE ARRAY. IT RETURNS A TUPLE OF ARRAYS, ONE FOR EACH DIMENSION OF THE INPUT 
#ARRAY. IN THIS CASE, SINCE x_train IS A 1-D ARRAY, IT RETURNS A TUPLE WITH ONE
#ARRAY CONTAINING THE INDICES OF THE ELEMENTS THAT SATISFY THE CONDITION.

[1 2 3 4 5 6 7 4]
(array([3, 7]),)
[4 4]
[4 4]

(array([1, 3, 5, 7]),)
(array([0, 2, 4, 6]),)


## Filtering NumPy with Boolean Index Lists

In [93]:
import numpy as np
x_train = np.array([1,2,3,4,5,6,7])
print(x_train)
'''
y = [True, False, True, False, True, False, True]
print(x_train[y])#PRINTS THE ELEMENTS IN THE ARRAY THAT CORRESPOND TO THE 
                 #TRUE VALUES IN THE BOOLEAN LIST y

filtered = []
for num in x_train:
     if num % 2 == 0:
        filtered.append(True)
     else:
        filtered.append(False)

print(filtered)
print(x_train[filtered])#PRINTS THE ELEMENTS IN THE ARRAY THAT CORRESPOND TO THE 
                        #TRUE VALUES IN THE BOOLEAN LIST filtered

'''
#A SHORT
filtered = x_train % 2 == 0#CREATES A BOOLEAN ARRAY WHERE EACH ELEMENT IS
                           #TRUE IF THE CORRESPONDING ELEMENT IN x_train IS
                           #EVEN, AND FALSE OTHERWISE

print(filtered)
print(x_train[filtered])#PRINTS THE ELEMENTS IN THE ARRAY THAT CORRESPOND TO THE
                        #TRUE VALUES IN THE BOOLEAN LIST filtered


[1 2 3 4 5 6 7]
[False  True False  True False  True False]
[2 4 6]
